FROM quay.io/centos/centos:stream10

RUN dnf -y install 'dnf-command(config-manager)' && \
    dnf -y config-manager --set-enabled crb && \
    dnf -y install epel-release

RUN dnf -y install \
        rsync \
        patch \
        git \
        jq

RUN dnf -y install \
        python3-dnf \
        python3-requests \
        python3-bugzilla \
        python3-jinja2 \
        koji \
        util-linux
