name: Weekly Build

on:
  schedule: # for scheduling to work this file must be in the default branch
  - cron: "0 0 * * 3" # repeat every Wednesday
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  prepare-repo-env:
    runs-on: ubuntu-latest
    outputs:
      repos: ${{ steps.get-repo-names.outputs.repos }}
    container:
      image: quay.io/podman/stable:latest
      options: --privileged

    steps:
    - name: Install dependencies
      run: |
        dnf -y install jq git nodejs

    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Get image from cache
      id: image-cache
      uses: actions/cache@v4
      with:
        path: |
          ./image/willit-deploy.tar
        key: container-${{ hashFiles('./podman/Containerfile') }}

    - name: Build Podman Image
      if: steps.image-cache.outputs.cache-hit != 'true'
      run: |
        bash ./build_image.sh
        mkdir -p ./image
        podman save willit-deploy > ./image/willit-deploy.tar

    - name: Get repo names
      id: get-repo-names
      run: |
        echo "repos=$( \
            jq -c \
              '[.repos[].RepoName | select( contains("-next") == false )]' \
              src/willit/willit-config.json \
          )" >> "$GITHUB_OUTPUT"

  gen-repo-pages:
    runs-on: ubuntu-latest
    needs: prepare-repo-env
    strategy:
      fail-fast: false
      matrix:
        repo: ${{ fromJson(needs.prepare-repo-env.outputs.repos) }}
    container:
      image: quay.io/podman/stable:latest
      options: --privileged

    steps:
    - name: Install dependencies
      run: |
        dnf -y install jq git nodejs

    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Filter config file
      run: |
        cat <<< $( \
            jq '{ repos:[.repos[] | select( .RepoName | contains("${{ matrix.repo }}") ) ]}' \
            src/willit/willit-config.json \
          ) > src/willit/willit-config.json

    - name: Get image from cache
      id: image-cache
      uses: actions/cache@v4
      with:
        path: |
          ./image/willit-deploy.tar
        key: container-${{ hashFiles('./podman/Containerfile') }}

    - name: Run process
      run: |
        podman load -i ./image/willit-deploy.tar
        bash ./deploy.sh

    - name: Upload output
      uses: actions/upload-artifact@v4
      with:
        name: output-${{ matrix.repo }}
        path: ./output/*
        retention-days: 1

  merge-repo-pages:
    runs-on: ubuntu-latest
    needs: gen-repo-pages
    container:
      image: quay.io/podman/stable:latest
      options: --privileged

    steps:
    - name: Install dependencies
      run: |
        dnf -y install jq git nodejs

    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Download repos output
      uses: actions/download-artifact@v4
      with:
        path: ./src/willit/

    - name: Get image from cache
      id: image-cache
      uses: actions/cache@v4
      with:
        path: |
          ./image/willit-deploy.tar
        key: container-${{ hashFiles('./podman/Containerfile') }}

    - name: Run merge process
      run: |
        rm src/willit/willit-config.json
        podman load -i ./image/willit-deploy.tar
        bash ./deploy.sh

    - name: Upload output
      uses: actions/upload-artifact@v4
      with:
        name: willit-output
        path: ./output/*
        retention-days: 1

  update-website:
    runs-on: ubuntu-latest
    needs: merge-repo-pages

    steps:
    - uses: actions/checkout@v4
      with:
        ref: 'gh-pages'
        path: 'gh-pages'

    - name: Download output files
      uses: actions/download-artifact@v4
      with:
        name: willit-output
        path: 'willit-output'
    
    - name: Sync web changes
      run: |
        mv willit-output/status-overall.html willit-output/index.html
        mkdir -p gh-pages/docs/
        rsync -azhuv --delete-after willit-output/ gh-pages/docs/

    - name: Commit report
      run: |
        git config --global user.name 'Sync Process'
        git config --global user.email 'sync-bot@users.noreply.github.com'
        git -C gh-pages commit -am "Sync pages"
        git -C gh-pages push
